services:
  bind9:
    container_name: bind9
#    image: internetsystemsconsortium/bind9:9.19 # OS/ARCH=linux/amd64
    image: psazevedo/bind9:9.19 # linux/arm64/v8 built with raspberry pi 4
    expose:
      - "53:53/udp"
      - "53:53/tcp"
      - "953:953/tcp"
    volumes:
      - "./data/config:/etc/bind"       # Configuration folder
      - "./data/cache:/var/cache/bind"  # Cache
      - "./data/zones:/var/lib/bind"    # secondary zones
      - "./data/logs:/var/log"          # Logs
    privileged: false
    platform: linux/amd64
    user: 